program FiboSum;
{
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
}

var
  fibo, next, tmp, sum : longint;
  { simple integer type can't handle values this big }

begin
  fibo := 0;
  next := 1;
  sum := 0;

  while (next < 4000000) do
  begin
    tmp := fibo + next;
    fibo := next;
    next := tmp;
    write(fibo, #9);
    if (fibo mod 2 = 0) then
      sum := sum + fibo;
  end;
  writeln;
  write('The sum of the EVEN members of the Fibonacci sequence ');
  writeln('up to 4 million is:');
  writeln(sum);

  readln;

end.